### ISSUE TITLE
"S" key turns clockwise and "D" key does nothing in keyboard_controls.py

### ISSUE THREAD

**Issue by gragundier** [threedworld-mit/tdw#262]
Was flipping through some demos to get a feel for tdw and ran into controls being bugged as described in title.  "W" and "A" key work as intended though.  The effect is mirrored for the arrow keys as well, so I think something is going on with the "move" and "turn" functions.  Here is my environment. 

> Build version 1.8.25
Unity Engine 2020.2.7f1
Python tdw module version 1.8.25

Python version: 3.9.6

**Comment by alters-mit** [comment]
@gragundier Thanks. I probably won't fix this because the keyboard controls API is getting an overhaul.

If you want to switch over to it, you can `git checkout v1.9_wip` and use the new `Keyboard` add-ons (add-ons are a new feature in TDW we're rolling out for the upcoming 1.9.0 release):

https://github.com/threedworld-mit/tdw/blob/v1.9_wip/Python/tdw/add_ons/keyboard.py

It's very similar to `KeyboardController` except that it can be appended to any controller.

**Comment by gragundier** [comment]
sweeeetttt thanks. Will do.

**Comment by alters-mit** [comment]
@gragundier  We just released TDW 1.9.0

[This document explains how to add keyboard controls to any controller.](https://github.com/threedworld-mit/tdw/blob/master/Documentation/lessons/humans/keyboard.md)

[This document has an overall v1.8 -> v1.9 upgrade guide.](https://github.com/threedworld-mit/tdw/blob/master/Documentation/upgrade_guides/v1.8_to_v1.9.md)

**Comment by gragundier** [comment]
Thanks for the heads up!
