### ISSUE TITLE
Further clarification on decision to close-source some of the library

### ISSUE THREAD

**Issue by agarret7** [threedworld-mit/tdw#298]
Hi all, first I wanted to say this library is incredibly cool. Thank you for all the time and effort that you've put into making this work.

I was somewhat surprised to see the decision to not release the C# source code. I noticed that the reasoning for this is framed in a negative way:

> TDW has been carefully designed so that the vast majority of use-cases should not require access to any back-end components of the platform.

However this starts from an implicit position that closed-source software has benefits in this sort of project (research-focused, not developed for a profit incentive), that are not explicitly expressed. I assume the authors agree there are costs to keeping this software closed-source, as they acknowledge the cost to modifiability and extensibility:

> However, we do recognize that certain users may need to, or want to, make modifications to the underlying C# code to suit specialized use cases. We therefore plan to consider applications for access to the back-end C# source code and Unity project on a case-by-case basis.

But I still struggle to understand exactly which positives informed the decision to keep the C# private, and selectively gate access to the code. Would you be willing to clarify a bit more what benefits you see from keeping those parts closed-source? I was also wondering if there are any plans in the future to make the full library open-source if it is sufficiently requested?

**Comment by jemsMIT** [comment]
@agarret7 Thank you for your interest in TDW!

So when we first publicly-released TDW, it was our feeling that most users would only really require access to the Python sources, and would be able to accomplish everything they needed to, regardless of use-case, with access to those sources.  It was our experience that a typical TDW user, from the larger research community, would almost certainly have the necessary Python skills. However it seemed far less likely that they would also have the C# experience, Unity development experience and other requirements necessary to work successfully on the TDW back-end.  Plus, we are a small team, and we were concerned our support load could increase significantly if we were also trying to support users working on back-end development, especially if those users did not have the requisite skills.

Having said all that, it may be time for us to take another look at making the C# sources and Unity TDW project more accessible.  If the number of users actually taking advantage of this access remains relatively small, and backend development is sufficiently well-documented, then the support impact on us should be manageable. 

However there is a separate issue with doing this, that we do not have a solution for yet. Certain new developments in TDW will utilize third-party plugins, which we have purchased. Publicly exposing the TDW Unity project -- and therefore the source code of those third-party plugins -- would break the EULA for those plugins and would require users to purchase those same plugins in order to use the TDW Unity project.  Of course, this is not an issue for the publicly-released platform in its current form. We will be working on how to potentially resolve this issue, but there is no definitive timeframe on when we would be doing so.

**Comment by agarret7** [comment]
Thank you for your reply!

> Publicly exposing the TDW Unity project -- and therefore the source code of those third-party plugins -- would break the EULA for those plugins and would require users to purchase those same plugins in order to use the TDW Unity project. Of course, this is not an issue for the publicly-released platform in its current form. We will be working on how to potentially resolve this issue, but there is no definitive timeframe on when we would be doing so.

So in other words, the current model of keeping the TDW Unity project closed would allow you to leverage these third-party plugins in the future without breaking the EULA? Am I understanding that correctly?

**Comment by instbldrjems** [comment]
@agarret7 Yes, that is correct.  Using those plugins at runtime, in the TDW build, is basically the same as if we had developed a game that used those plugins. This is basically what the Unity Asset Store is for.  However making the TDW Unity project available, with the source code and DLLs for those 3rd-party plugins in the project, is a very different thing.
