### ISSUE TITLE
Inserting additional light sources

### ISSUE THREAD

**Issue by Maitreyapatel** [threedworld-mit/tdw#302]
Hello, 

This is a great and easy open-source physics-simulation. Kudos to the team working and updating it constantly.

I was working on a creating few simple simulations for the project. Here, I'm using `TDWUtils.create_empty_room(25, 25)` to initiate the environment. However, because of the light source position, it's creating unwanted dark shades to certain objects like a sphere. Therefore, to make such objects visible at all angles, I want to add additional light sources. However, I could not find a way to do that.

If there is any method to do so, then can someone please redirect me to the documentation? If not, then this issue can be a feature request !!

Thanks in advance.

**Comment by alters-mit** [comment]
@Maitreyapatel 

> This is a great and easy open-source physics-simulation. Kudos to the team working and updating it constantly.

Thanks! 😄 

> I want to add additional light sources. However, I could not find a way to do that.

Right now, we don't plan to allow users to add light sources because it's harder than it might seem to design a reasonable-looking lighting setup. Unless you're a lighting designer, most lighting setups will look very strange or unrealistic.

TDW does include commands to adjust the lighting in the scene. For your purposes, you might be able to simply rotate the directional light: https://github.com/threedworld-mit/tdw/blob/master/Documentation/api/command_api.md#rotate_directional_light_by

**Comment by alters-mit** [comment]
Closing because this isn't a feature that will be implemented in TDW LTS
