### ISSUE TITLE
Long render time for tdw tutorial "proc_gen_kitchen_minimal"

### ISSUE THREAD

**Issue by wetoo-cando** [threedworld-mit/tdw#597]
Thanks for the great work!

I tried the `proc_gen_kitchen_minimal' tutorial today and saw that it takes a long time to render. How long I cannot say, as I could not monitor at after work hours. But rendering the two images definitely did not complete in less than 10 minutes. 

I am on a Windows desktop PC with intel i9, 64GB RAM, NVIDIA RTX 3090 with 24GB VRAM, so the PC specs shouldn't be a problem.

```>python tdw\Python\example_controllers\scene_setup_high_level\proc_gen_kitchen_minimal.py _high_level\proc_gen_kitchen_minimal.py
Images will be saved to: C:\Users\Rahul\tdw_example_controller_output\proc_gen_kitchen_minimal
Your installed tdw Python module is up to date with PyPi.
Build version 1.11.23
Unity Engine 2020.3.24f1
Python tdw module version 1.11.23
```

Also observed similar behavior in other tutorials. E.g. the `vr/oculus_touch_output_Data` takes several minutes to just render the initial scene onto the display / headset.

Is this expected behavior or is there any explanation why it takes so long?

**Comment by alters-mit** [comment]
This is expected behavior. You are downloading objects and loading them into memory.

To learn about how objects are loaded to and persist in memory, [read this](https://github.com/threedworld-mit/tdw/blob/master/Documentation/lessons/core_concepts/objects.md).

You can download asset bundles and use the local files at runtime, rather than downloading them from the S3 server every time. The initial scene setup will be faster because you're not downloading anything but it'll still be slow because you have to load the objects into memory. For more information, [read this](https://github.com/threedworld-mit/tdw/blob/master/Documentation/lessons/misc/download_asset_bundles.md).
